name: 'Dependabot Fetch Metadata'
description: 'Fetch metadata for Dependabot PRs'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
outputs:
  dependency-name:
    description: 'The name of the dependency being updated'
  dependency-type:
    description: 'The type of the dependency being updated'
  update-type:
    description: 'The type of update being performed'
runs:
  using: 'composite'
  steps:
    - name: Fetch Dependabot metadata
      id: fetch-metadata
      uses: dependabot/fetch-metadata@v2
      with:
        github-token: ${{ inputs.github-token }}

    - name: Set output - dependency-name
      run: echo "dependency-name=${{ steps.fetch-metadata.outputs.dependency-name }}" >> $GITHUB_ENV
    - name: Set output - dependency-type
      run: echo "dependency-type=${{ steps.fetch-metadata.outputs.dependency-type }}" >> $GITHUB_ENV
    - name: Set output - update-type
      run: echo "update-type=${{ steps.fetch-metadata.outputs.update-type }}" >> $GITHUB_ENV
