name: Dependabot Pull Request
on: pull_request_target
jobs:
  build:
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: eamonnk418/github-dependabot-action@main
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"