name: Dependabot Pull Request

on: pull_request_target

permissions: 
    pull-requests: read

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: github.actor == 'dependabot[bot]'
        steps:
            - name: Fetch Dependabot metadata
              id: dependabot-metadata
              uses: dependabot/fetch-metadata@v1
              with:
                alert-lookup: true
                compat-lookup: true
                github-token: "${{ secrets.GITHUB_TOKEN }}"
