name: Dependabot fetch metadata
on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch metadata
        uses: ./.github/actions/dependabot-fetch-metadata
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Output metadata
        run: |
          echo "Dependency Name: ${{ env.dependency-name }}"
          echo "Dependency Type: ${{ env.dependency-type }}"
          echo "Update Type: ${{ env.update-type }}"
